Repository TedMoon99/Android-Review, pull requests merged in 2024-06, with the labels that each got.

#2 [#1] Android review01 ted moon
  .idea/gradle.xml
  android_review01_tedmoon/build.gradle.kts
  android_review01_tedmoon/src/main/java/com/example/android_review01_tedmoon/CustomAdapter.kt
  android_review01_tedmoon/src/main/java/com/example/android_review01_tedmoon/MainActivity.kt
  android_review01_tedmoon/src/main/java/com/example/android_review01_tedmoon/MainFragment.kt
  android_review01_tedmoon/src/main/res/layout/activity_main.xml
  android_review01_tedmoon/src/main/res/layout/fragment_main.xml
  android_review01_tedmoon/src/main/res/layout/row_main.xml
  android_review01_tedmoon/src/main/res/values/colors.xml
  android_review01_tedmoon/src/main/res/values/themes.xml
Labels: 문제 풀이 완료, 코드 리뷰해주세요

#6 Test Read Me
  README.md
Labels: What The Fuck!!!

#12 [#10] Android review02 baek08102
  .idea/deploymentTargetSelector.xml
  .idea/gradle.xml
  android_review02_baek08102/.gitignore
  android_review02_baek08102/README.md
  android_review02_baek08102/build.gradle.kts
  android_review02_baek08102/proguard-rules.pro
  android_review02_baek08102/src/androidTest/java/com/example/android_review02_baek08102/ExampleInstrumentedTest.kt
  android_review02_baek08102/src/main/AndroidManifest.xml
  android_review02_baek08102/src/main/java/com/example/android_review02_baek08102/MainActivity.kt
  android_review02_baek08102/src/main/java/com/example/android_review02_baek08102/MainFragment.kt
  android_review02_baek08102/src/main/java/com/example/android_review02_baek08102/MyAdapter.kt
  android_review02_baek08102/src/main/res/drawable/ic_launcher_background.xml
  android_review02_baek08102/src/main/res/drawable/ic_launcher_foreground.xml
  android_review02_baek08102/src/main/res/layout/activity_main.xml
  android_review02_baek08102/src/main/res/layout/fragment_main.xml
  android_review02_baek08102/src/main/res/layout/row_main.xml
  android_review02_baek08102/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android_review02_baek08102/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android_review02_baek08102/src/main/res/mipmap-hdpi/ic_launcher.webp
  android_review02_baek08102/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android_review02_baek08102/src/main/res/mipmap-mdpi/ic_launcher.webp
  android_review02_baek08102/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android_review02_baek08102/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android_review02_baek08102/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android_review02_baek08102/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android_review02_baek08102/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android_review02_baek08102/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android_review02_baek08102/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  android_review02_baek08102/src/main/res/values-night/themes.xml
  android_review02_baek08102/src/main/res/values/colors.xml
  android_review02_baek08102/src/main/res/values/strings.xml
  android_review02_baek08102/src/main/res/values/themes.xml
  android_review02_baek08102/src/test/java/com/example/android_review02_baek08102/ExampleUnitTest.kt
  android_review03_baek08102/.gitignore
  android_review03_baek08102/build.gradle.kts
  android_review03_baek08102/proguard-rules.pro
  android_review03_baek08102/src/androidTest/java/com/example/android_review03_baek08102/ExampleInstrumentedTest.kt
  android_review03_baek08102/src/main/AndroidManifest.xml
  android_review03_baek08102/src/main/java/com/example/android_review03_baek08102/MainActivity.kt
  android_review03_baek08102/src/main/res/drawable/ic_launcher_background.xml
  android_review03_baek08102/src/main/res/drawable/ic_launcher_foreground.xml
  android_review03_baek08102/src/main/res/layout/activity_main.xml
  android_review03_baek08102/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android_review03_baek08102/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android_review03_baek08102/src/main/res/mipmap-hdpi/ic_launcher.webp
  android_review03_baek08102/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android_review03_baek08102/src/main/res/mipmap-mdpi/ic_launcher.webp
  android_review03_baek08102/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android_review03_baek08102/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android_review03_baek08102/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android_review03_baek08102/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android_review03_baek08102/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android_review03_baek08102/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android_review03_baek08102/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  android_review03_baek08102/src/main/res/values-night/themes.xml
  android_review03_baek08102/src/main/res/values/colors.xml
  android_review03_baek08102/src/main/res/values/strings.xml
  android_review03_baek08102/src/main/res/values/themes.xml
  android_review03_baek08102/src/test/java/com/example/android_review03_baek08102/ExampleUnitTest.kt
  settings.gradle.kts
Labels: 문제 풀이 완료
